version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: todos-postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data